name: Download a Build Artifact

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2.4.2
      
      - name: Tar files
        run: tar -cvf reporters.tar ./package.json
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Upload reporters
          path: reporters.tar
