name: Download a Build Artifact

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2.4.2
      
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: Artifact
          path: ./package.json
