name: automerge
on:
  pull_request:
    types:
      - opened
    branches:
      - main
jobs:
  automerge:
    if: startsWith(github.head_ref, "update-")
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - id: create tag
        name: create tag
        run: echo TODO
