name: Custom action

on: workflow_dispatch

jobs:
  custom-action:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.4.2

      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16

#       - name: Setup pnpm
#         uses: pnpm/action-setup@v2.2.2
#         with:
#           version: 7.3.0
#           run_install: |
#             - args: [--frozen-lockfile, --prod, --ignore-scripts]

      - name: run custom actions
        uses: ./
        with:
          sprint: "迭代"
          branch: "master"

      - name: next
        if: always()
        run: echo "always 进行下一步操作"

      - name: if-failed
        if: failure()
#         run: >
#           curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=20349830-109c-4f90-80c2-a220f2c0e0bb' -H 'Content-Type: application/json' -d '{ 
#             "msgtype": "template_card"
#             "template_card": {
#               "card_type": "text_notice",
#               "source": {
#                 "desc": "open-test"
#               },
#               "main_title": {
#                 "title": "❌ 插槽测试未通过！"
#               },
#               "sub_title_text": "请分析测试报告",
#               "horizontal_content_list": [
#                 {
#                   "keyname":"测试报告",
#                   "value": "P8066-master",
#                   "type": 1,
#                   "url": "https://github.com/BangWork/open-test/actions/runs/2812650295"
#                 }
#               ],
#               "card_action": {
#                 "type": 1,
#                 "url": "https://github.com/BangWork/open-test/actions"
#               },
#             }
#           }'
        run: >
          curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=20349830-109c-4f90-80c2-a220f2c0e0bb' -H 'Content-Type: application/json' -d '{
            "msgtype": "template_card",
            "template_card": {
              "card_type": "text_notice",
              "card_action": {
                "type": 1,
                "url": "https://github.com/BangWork/open-test/actions"
              },
              "source": {
                "desc": "open-test"
              },
              "main_title": {
                "title": "❌ 插槽测试未通过！"
              },
              "sub_title_text": "请分析测试报告",
              "horizontal_content_list": [
                {
                  "keyname":"测试报告",
                  "value": "P8066-master",
                  "type": 1,
                  "url": "https://github.com/BangWork/open-test/actions/runs/2812650295"
                }
              ],
            }
          }'
