name: Context testing
on: 
  workflow_dispatch

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.4.2

      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: run custom actions
        run: node actions/index.js
        
