name: Docker Login

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          registry: lzspace/ones-open-test
          username: lzspace
          password: Mnislz128340
          ecr: auto
          logout: true
