name: manually triiger test

on:
  workflow_dispatch:
    inputs:
      Branch:
        description: '待测试分支号'
        required: true
        default: 'master'
        type: string
      Sprint:
        description: '请填写所属迭代'
        required: true
        type: string
      UserInfo:
        description: '使用用户账号、密码，如果没有填写则应用默认账号'
        type: string
        required: false
      
jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:
      - run: echo 分支号 ${{ inputs.Branch }}
      - run: echo 所属迭代 ${{ inputs.Branch }}
