name: manually docker trigger

env:
  DOCKERHUB_REPO: lzspace/ones-open-test

on: 
  workflow_dispatch:
    inputs:
      Branch:
        description: '待测试分支号'
        required: true
        default: 'master'
        type: string
      Sprint:
        description: '请填写所属迭代'
        required: true
        type: string
      UserInfo:
        description: '使用用户账号、密码，如果没有填写则应用默认账号'
        type: string
        required: false

jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - run: docker run --name open-test-container -i --rm --env OPEN_ENV_BRANCH=master -v $PWD/reporters:/open-test/reporters lzspace/ones-open-test