name: manually docker trigger

env:
  DOCKERHUB_REPO: lzspace/ones-open-test:intel

on: 
  workflow_dispatch:
    inputs:
      Branch:
        description: '待测试分支号'
        required: true
        default: 'master'
        type: string
      Sprint:
        description: '请填写所属迭代'
        required: true
        type: string
      UserInfo:
        description: '使用用户账号、密码，如果没有填写则应用默认账号'
        type: string
        required: false

jobs:
  node-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Run open-test docker
        run: docker run --name open-test-container -i --rm \
         --env OPEN_ENV_BRANCH=${{ inputs.Branch }} \
         --env OPEN_ENV_USERINFO=${{ inputs.UserInfo }} \
         --env OPEN_ENV_SPRINT=${{ inputs.Sprint }} \
         -v $PWD/reporters:/open-test/reporters \
         $DOCKERHUB_REPO
