name: Test

on:
  workflow_dispatch:
    inputs:
      sprint:
        description: "Your sprint name."
        required: true
      branch:
        description: "The branch name what you want to test."
        default: "master"
        required: true


jobs:
  log-context:
    runs-on: ubuntu-latest
    
    env:
     DESCRIPTION: ${{ inputs.sprint - inputs.branch }}

    steps:
      - name: $DESCRIPTION
        run: echo $DESCRIPTION 
